index:
    path: /student
    controller: App\Controller\StudentController::index

teacher:
    path: /teacher
    controller: App\Controller\TeacherController::index

## TEACHER
createExam:
    path: /create-exam
    controller: App\Controller\TeacherController::createExam

storeExam:
    path: /store-exam
    controller: App\Controller\TeacherController::storeExam

deleteExam:
    path: /delete-exam/{id}
    controller: App\Controller\TeacherController::deleteExam

createQuestions:
    path: /create-questions/{category}
    controller: App\Controller\TeacherController::createQuestions

selectQuestions:
    path: /select-questions/exam/{id}
    controller: App\Controller\TeacherController::selectQuestions

storeExamQuestions:
    path: /store-exam-questions/{id}
    controller: App\Controller\TeacherController::storeExamQuestions

storeQuestions:
    path: /store-questions
    controller: App\Controller\TeacherController::storeQuestions

deleteQuestion:
    path: /delete-question/{id}
    controller: App\Controller\TeacherController::deleteQuestion

questionsList:
    path: /questions-list/{id}
    controller: App\Controller\TeacherController::questionsList

## STUDENT
#### MAIN ACTIVITIES
exams:
    path: /exams
    controller: App\Controller\StudentController::allExams

exam:
    path: /exam/{id}
    controller: App\Controller\StudentController::singleExam

categories:
    path: /categories
    controller: App\Controller\StudentController::categories

fillExam:
    path: /fill-exam/user/{user}/exam/{exam}
    controller: App\Controller\StudentController::fillExam


#### LOGGING
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout