index:
    path: /
    controller: App\Controller\SecurityController::index

## TEACHER
teacher:
    path: /teacher
    controller: App\Controller\TeacherController::index

createExam:
    path: /teacher/exam/create/{category}
    controller: App\Controller\TeacherController::createExam

storeExam:
    path: /teacher/exam/store
    controller: App\Controller\TeacherController::storeExam

deleteExam:
    path: /teacher/exam/delete/{id}
    controller: App\Controller\TeacherController::deleteExam

studentsResults:
    path: /exam/results/{id}
    controller: App\Controller\TeacherController::studentsResults

showExam:
    path: /teacher/exam/show/{id}
    controller: App\Controller\TeacherController::showExam

createQuestions:
    path: /teacher/question/create/{category}
    controller: App\Controller\TeacherController::createQuestions

selectExamQuestions:
    path: /teacher/exam/{id}/select/question
    controller: App\Controller\TeacherController::selectExamQuestions

storeExamQuestions:
    path: /teacher/exam/{id}/question/store/
    controller: App\Controller\TeacherController::storeExamQuestions

storeQuestions:
    path: /teacher/question/store
    controller: App\Controller\TeacherController::storeQuestions

deleteQuestion:
    path: /teacher/question/delete/{questionId}
    controller: App\Controller\TeacherController::deleteQuestion

deleteExamQuestion:
    path: /teacher/exam/{examId}/question/{questionId}/delete
    controller: App\Controller\TeacherController::deleteExamQuestion

questionsList:
    path: /teacher/exam/questions/{id}
    controller: App\Controller\TeacherController::questionsList

createSubject:
    path: /teacher/subject/create
    controller: App\Controller\TeacherController::createSubject

subject:
    path: /teacher/subject/{id}
    controller: App\Controller\TeacherController::singleSubject

updateSubject:
    path: /teacher/subject/{id}/update
    controller: App\Controller\TeacherController::updateSubject

storeSubject:
    path: /teacher/subject/store
    controller: App\Controller\TeacherController::storeSubject

## STUDENT
#### MAIN ACTIVITIES
student:
    path: /student
    controller: App\Controller\StudentController::index

subjects:
    path: /subjects
    controller: App\Controller\TeacherController::allSubjects

fillExam:
    path: /exam/{examId}/fill/user/{userId}
    controller: App\Controller\StudentController::fillExam

storeExamResults:
    path: /exam/{examId}/store
    controller: App\Controller\StudentController::storeExamResults

## COMONN
exams:
    path: /exams
    controller: App\Controller\CommonController::allExams

exam:
    path: /exam/{id}
    controller: App\Controller\CommonController::singleExam

checkResult:
    path: /exam/{examId}/show/results/user/{userId}
    controller: App\Controller\CommonController::checkResult


#### LOGGING
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout