index:
    path: /
    controller: App\Controller\SecurityController::index

student:
    path: /student
    controller: App\Controller\StudentController::index

teacher:
    path: /teacher
    controller: App\Controller\TeacherController::index

## TEACHER
createExam:
    path: /teacher/exam/create/{category}
    controller: App\Controller\TeacherController::createExam

storeExam:
    path: /teacher/exam/store
    controller: App\Controller\TeacherController::storeExam

deleteExam:
    path: /teacher/exam/delete/{id}
    controller: App\Controller\TeacherController::deleteExam

showExam:
    path: /teacher/exam/show/{id}
    controller: App\Controller\TeacherController::showExam

createQuestions:
    path: /teacher/question/create/{category}
    controller: App\Controller\TeacherController::createQuestions

selectExamQuestions:
    path: /teacher/question/select/exam/{id}
    controller: App\Controller\TeacherController::selectExamQuestions

storeExamQuestions:
    path: /teacher/exam-question/store/{id}
    controller: App\Controller\TeacherController::storeExamQuestions

storeQuestions:
    path: /teacher/question/store
    controller: App\Controller\TeacherController::storeQuestions

deleteQuestion:
    path: /teacher/question/delete/{questionId}
    controller: App\Controller\TeacherController::deleteQuestion

deleteExamQuestion:
    path: /teacher/exam/{examId}/question/{questionId}/delete
    controller: App\Controller\TeacherController::deleteExamQuestion

questionsList:
    path: /teacher/exam/questions/{id}
    controller: App\Controller\TeacherController::questionsList

createSubject:
    path: /teacher/subject/create
    controller: App\Controller\TeacherController::createSubject

subject:
    path: /teacher/subject/{id}
    controller: App\Controller\TeacherController::singleSubject

updateSubject:
    path: /teacher/subject/update/{id}
    controller: App\Controller\TeacherController::updateSubject

storeSubject:
    path: /teacher/subject/store
    controller: App\Controller\TeacherController::storeSubject

## STUDENT
#### MAIN ACTIVITIES
subjects:
    path: /subjects
    controller: App\Controller\TeacherController::allSubjects

fillExam:
    path: /exam/fill/{examId}/user/{userId}
    controller: App\Controller\StudentController::fillExam

storeExamResults:
    path: /exam/store/{examId}
    controller: App\Controller\StudentController::storeExamResults

checkResult:
    path: /exam/show/results/{examId}
    controller: App\Controller\StudentController::checkResult

## COMONN
exams:
    path: /exams
    controller: App\Controller\CommonController::allExams

exam:
    path: /exam/{id}
    controller: App\Controller\CommonController::singleExam


#### LOGGING
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout